var Notifications = Notifications || {};

Notifications.layer = {
    SUBLAYER_SELECTION_CHANGED: "layer.SUBLAYER_SELECTION_CHANGED",
    LAYER_SELECTION_CHANGED: "layer.LAYER_SELECTION_CHANGED"
};

Notifications.data = {
    GENERIC_DATA_CHANGED: "data.GENERIC_DATA_CHANGED",
    POTHOLE_CHANGED: "data.POTHOLE_CHANGED",
    RAT_BITES_CHANGED: "data.RAT_BITES_CHANGED",
    ABANDONED_VEHICLES_CHANGED: "data.ABANDONED_VEHICLES_CHANGED",
    LIGHT_OUT_SINGLE_CHANGED: "data.LIGHT_OUT_SINGLE_CHANGED",
    LIGHT_OUT_ALL_CHANGED: "data.LIGHT_OUT_SINGLE_CHANGED",
    DIVVY_BIKES_CHANGED: "data.DIVVY_BIKES_CHANGED",
    BUS_CHANGED: "data.BUS_CHANGED",
    BUS_SELECTION_CHANGED: "data.BUS_SELECTION_CHANGED",
    WEATHER_CHANGED: "data.WEATHER_CHANGED",
    DIRECTION_CHANGED: "data.DIRECTION_CHANGED",

    // For future uses
    YELP_FOOD_CHANGED: "data.YELP_FOOD_CHANGED",
    TWITTER_CHANGED: "data.TWITTER_CHANGED",
    FOOD_INSPECTION_CHANGED: "data.FOOD_INSPECTION_CHANGED",
    TRAFFIC_CONGESTION_CHANGED: "data.TRAFFIC_CONGESTION_CHANGED"
};

Notifications.data.crime = {
    /// CRIME notification
    CRIME_CHANGED: "data.CRIME_CHANGED", //Crime relative current selection updated
    CRIME_CATEGORY1_CHANGED: "data.crime.CRIME_CATEGORY1_CHANGED",
    CRIME_CATEGORY2_CHANGED: "data.crime.CRIME_CATEGORY2_CHANGED",
    CRIME_CATEGORY3_CHANGED: "data.crime.CRIME_CATEGORY3_CHANGED",
    CRIME_CATEGORY4_CHANGED: "data.crime.CRIME_CATEGORY4_CHANGED",
    CRIME_MONTH_TOTAL_CHANGED: "data.CRIME_MONTH_TOTAL_CHANGED", //Trend total Crime last 5 years relative current Selection with granularity month
    CRIME_MONTH_TYPE_CHANGED: "data.CRIME_MONTH_TOTAL_CHANGED" //Trend Crime last 5 years grouped by type relative current Selection with granularity month

};

Notifications.selection = {
    SELECTION_CHANGED: "selection.SELECTION_CHANGED",
    SELECTION_POINTS_CHANGED: "selection.SELECTION_POINTS_CHANGED",
    SELECTION_MODE_CHANGED: "selection.SELECTION_MODE_CHANGED"
};

Notifications.timeInterval = {
    TIME_INTERVAL_CHANGED: "timeInterval.TIME_INTERVAL_CHANGED"
};


