var Notifications = Notifications || {};

Notifications.layer = {
    SUBLAYER_SELECTION_CHANGED: "layer.SUBLAYER_SELECTION_CHANGED",
    LAYER_SELECTION_CHANGED: "layer.LAYER_SELECTION_CHANGED"
};

Notifications.data = {
    GENERIC_DATA_CHANGED: "data.GENERIC_DATA_CHANGED",
    POTHOLE_CHANGED: "data.POTHOLE_CHANGED",
    POTHOLE_SELECTION_CHANGED: "data.POTHOLE_SELECTION_CHANGED",
    RAT_BITES_CHANGED: "data.RAT_BITES_CHANGED",
    ABANDONED_VEHICLES_CHANGED: "data.ABANDONED_VEHICLES_CHANGED",
    ABANDONED_VEHICLES_SELECTION_CHANGED: "data.ABANDONED_VEHICLES_SELECTION_CHANGED",
    LIGHT_OUT_SINGLE_CHANGED: "data.LIGHT_OUT_SINGLE_CHANGED",
    LIGHT_OUT_SINGLE_SELECTION_CHANGED: "data.LIGHT_OUT_SINGLE_SELECTION_CHANGED",
    LIGHT_OUT_ALL_CHANGED: "data.LIGHT_OUT_SINGLE_CHANGED",
    LIGHT_ALL_OUT_SELECTION_CHANGED: "data.LIGHT_ALL_OUT_SELECTION_CHANGED",
    DIVVY_BIKES_CHANGED: "data.DIVVY_BIKES_CHANGED",
    DIVVY_BIKES_SELECTION_CHANGED: "data.DIVVY_BIKES_SELECTION_CHANGED",
    BUS_CHANGED: "data.BUS_CHANGED",
    BUS_SELECTION_CHANGED: "data.BUS_SELECTION_CHANGED",
    WEATHER_CHANGED: "data.WEATHER_CHANGED",
    DIRECTION_CHANGED: "data.DIRECTION_CHANGED",
    FOOD_CHANGED: "data.FOOD_CHANGED",

    // For future uses
    YELP_RESTAURANT_CHANGED: "data.YELP_RESTAURANT_CHANGED",
    YELP_BAR_CHANGED: "data.YELP_BAR_CHANGED",
    TWITTER_CHANGED: "data.TWITTER_CHANGED",
    FOOD_INSPECTION_CHANGED: "data.FOOD_INSPECTION_CHANGED",
    TRAFFIC_CONGESTION_CHANGED: "data.TRAFFIC_CONGESTION_CHANGED",

    // Notification when some data change
    NOTIFICATION_AVAILABLE: "data.NOTIFICATION_AVAILABLE"
};

Notifications.data.crime = {
    CRIME_SELECTION_CHANGED: "data.crime.CRIME_SELECTION_CHANGED",
    CRIME_CATEGORY1_CHANGED: "data.crime.CRIME_CATEGORY1_CHANGED",
    CRIME_CATEGORY2_CHANGED: "data.crime.CRIME_CATEGORY2_CHANGED",
    CRIME_CATEGORY3_CHANGED: "data.crime.CRIME_CATEGORY3_CHANGED",
    CRIME_CATEGORY4_CHANGED: "data.crime.CRIME_CATEGORY4_CHANGED",
    CRIME_MONTH_TOTAL_CHANGED: "data.CRIME_MONTH_TOTAL_CHANGED", //Trend total Crime last 5 years relative current Selection with granularity month
    CRIME_MONTH_TYPE_CHANGED: "data.CRIME_MONTH_TOTAL_CHANGED" //Trend Crime last 5 years grouped by type relative current Selection with granularity month

};

Notifications.selection = {
    SELECTION_CHANGED: "selection.SELECTION_CHANGED",
    SELECTION_POINTS_CHANGED: "selection.SELECTION_POINTS_CHANGED",
    SELECTION_MODE_CHANGED: "selection.SELECTION_MODE_CHANGED"
};

Notifications.enhanceIcon = {
    SELECTION_CHANGED: "enhanceIcon.SELECTION_CHANGED"
};

Notifications.timeInterval = {
    TIME_INTERVAL_CHANGED: "timeInterval.TIME_INTERVAL_CHANGED"
};

Notifications.position = {
    POSITION_CHANGED: "position.POSITION_CHANGED"
};


Notifications.graphs = {
    GRAPH_LAYER_SELECTED_CHANGED: "graphs.GRAPH_LAYER_SELECTED_CHANGED",
    GRAPH_SUBLAYER_SELECTED_CHANGED: "graphs.GRAPH_SUBLAYER_SELECTED_CHANGED"
};
