var Notifications = Notifications || {};

Notifications.layer = {
    SUBLAYER_SELECTION_CHANGED: "layer.SUBLAYER_SELECTION_CHANGED",
    LAYER_SELECTION_CHANGED: "layer.LAYER_SELECTION_CHANGED"
};

Notifications.data = {
    GENERIC_DATA_CHANGED: "data.GENERIC_DATA_CHANGED",
    POTHOLE_CHANGED: "data.POTHOLE_CHANGED",
    ABANDONED_VEHICLES_CHANGED: "data.ABANDONED_VEHICLES_CHANGED",
    LIGHT_OUT_SINGLE_CHANGED: "data.LIGHT_OUT_SINGLE_CHANGED",
    LIGHT_OUT_ALL_CHANGED: "data.LIGHT_OUT_SINGLE_CHANGED",
    DIVVY_BIKES_CHANGED: "data.DIVVY_BIKES_CHANGED",
    BUS_CHANGED: "data.BUS_CHANGED",
    WEATHER_CHANGED: "data.WEATHER_CHANGED",

    // For future uses
    YELP_FOOD_CHANGED: "data.YELP_FOOD_CHANGED",
    TWITTER_CHANGED: "data.TWITTER_CHANGED",
    FOOD_INSPECTION_CHANGED: "data.FOOD_INSPECTION_CHANGED",
    TRAFFIC_CONGESTION_CHANGED: "data.TRAFFIC_CONGESTION_CHANGED"
};

Notifications.selection = {
    SELECTION_CHANGED: "selection.SELECTION_CHANGED"
};


